@extends('layouts.app')

@section('title', $product['name'].' — Kembang Hijab')
@section('meta_description', $product['description'])

@section('content')
    <section class="mx-auto max-w-7xl px-4 py-10 sm:px-6 lg:px-8">
        <a href="{{ route('products.index') }}" class="text-sm font-bold uppercase hover:underline">← Back to collection</a>
        <div class="mt-8 grid gap-8 lg:grid-cols-[1.05fr_.95fr]">
            <div class="arcade-checkerboard p-6 sm:p-10"><div class="aspect-[.9] overflow-hidden border border-black bg-[#f3e5df]"><img src="{{ $product['image'] }}" alt="{{ $product['name'] }}" width="900" height="1125" fetchpriority="high" class="h-full w-full object-cover"></div><div class="mt-5 flex justify-center gap-2"><button class="arcade-button arcade-button-ghost" type="button">3D</button><button class="arcade-button arcade-button-ghost" type="button">AR</button></div></div>
            <div class="flex flex-col justify-center"><p class="text-xs font-bold uppercase tracking-[.2em] text-[#faa21f]">{{ $product['category'] }} · {{ $product['rating'] }} ★ · {{ $product['reviews'] }} reviews</p><h1 class="mt-4 text-4xl font-bold uppercase leading-tight sm:text-5xl">{{ $product['name'] }}</h1><div class="mt-5 flex items-center gap-3"><strong class="text-2xl">Rp{{ number_format($product['price'], 0, ',', '.') }}</strong>@if($product['old_price'])<del class="text-sm text-[#737373]">Rp{{ number_format($product['old_price'], 0, ',', '.') }}</del><span class="arcade-tag bg-[#faa21f]">SALE</span>@endif</div><p class="mt-7 max-w-lg text-sm leading-7 text-[#737373]">{{ $product['description'] }}</p><div class="mt-7 border-y border-black py-6"><p class="text-sm font-bold uppercase">Select variant</p><div class="mt-4 flex flex-wrap gap-2"><button type="button" class="arcade-button arcade-button-ghost" aria-pressed="true">Cream</button><button type="button" class="arcade-button arcade-button-ghost">Brown</button><button type="button" class="arcade-button arcade-button-ghost">Dusty Pink</button></div></div><div class="mt-7 flex gap-3"><form method="POST" action="{{ route('cart.items.store') }}" class="flex flex-1 gap-2">@csrf<input type="hidden" name="slug" value="{{ $product['slug'] }}"><label class="sr-only" for="quantity">Quantity</label><input id="quantity" name="quantity" type="number" min="1" max="99" value="1" class="w-20 border border-black bg-[#f3e5df] px-3 text-center"><button class="arcade-button arcade-button-primary flex-1 uppercase" type="submit">Add to cart</button></form><form method="POST" action="{{ route('wishlist.toggle') }}">@csrf<input type="hidden" name="slug" value="{{ $product['slug'] }}"><button class="arcade-button arcade-button-ghost px-4" type="submit" aria-label="Save {{ $product['name'] }} to wishlist">♡</button></form></div><p class="mt-5 text-xs text-[#737373]">IN STOCK · Free shipping over Rp300.000 · Easy returns</p></div>
        </div>
        <div class="mt-16 border-t border-black pt-10"><p class="text-xs font-bold uppercase tracking-[.2em] text-[#faa21f]">You may also like</p><div class="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-3">@foreach($relatedProducts as $item)<a href="{{ route('products.show', $item['slug']) }}" class="arcade-card group"><img src="{{ $item['image'] }}" alt="{{ $item['name'] }}" width="900" height="1125" loading="lazy" class="aspect-[4/5] w-full object-cover transition group-hover:scale-[1.02]"><h2 class="mt-3 text-sm font-bold uppercase">{{ $item['name'] }}</h2><p class="mt-2 text-sm">Rp{{ number_format($item['price'], 0, ',', '.') }}</p></a>@endforeach</div></div>
    </section>
@endsection
