<?php

return [
    'categories' => [
        [
            'slug' => 'pashmina',
            'name' => 'Pashmina',
            'description' => 'Flowy silhouettes for effortless everyday styling.',
            'tone' => 'from-[#d8c4bd] via-[#efe3d9] to-[#b99a62]',
        ],
        [
            'slug' => 'voal',
            'name' => 'Voal',
            'description' => 'Lightweight, breathable, and easy to style.',
            'tone' => 'from-[#e8cfcf] via-[#f4e7e2] to-[#c58f9d]',
        ],
        [
            'slug' => 'square',
            'name' => 'Square',
            'description' => 'Timeless square scarves for every occasion.',
            'tone' => 'from-[#b99a62] via-[#d2b99b] to-[#6f5146]',
        ],
        [
            'slug' => 'inner',
            'name' => 'Inner',
            'description' => 'Comfortable essentials to keep every look in place.',
            'tone' => 'from-[#d7c1b4] via-[#f4e9dd] to-[#a88b7b]',
        ],
    ],
    'products' => [
        [
            'id' => 1,
            'slug' => 'pashmina-satin-moonlight',
            'name' => 'Pashmina Satin Moonlight',
            'category' => 'Pashmina',
            'price' => 149000,
            'old_price' => 179000,
            'rating' => 4.9,
            'reviews' => 128,
            'tag' => 'Best seller',
            'color' => 'from-[#d8c4bd] via-[#efe3d9] to-[#b99a62]',
            'image' => 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?auto=format&fit=crop&w=900&q=85',
            'description' => 'Pashmina satin dengan kilau lembut yang jatuh cantik untuk menemani momen spesial maupun gaya sehari-hari.',
        ],
        [
            'id' => 2,
            'slug' => 'voal-paris-rose',
            'name' => 'Voal Paris Rose',
            'category' => 'Voal',
            'price' => 119000,
            'old_price' => null,
            'rating' => 4.8,
            'reviews' => 96,
            'tag' => 'New arrival',
            'color' => 'from-[#e8cfcf] via-[#f4e7e2] to-[#c58f9d]',
            'image' => 'https://images.unsplash.com/photo-1584184924103-e310d9dc82fc?auto=format&fit=crop&w=900&q=85',
            'description' => 'Voal premium bertekstur ringan dengan warna rose yang manis dan mudah dipadukan.',
        ],
        [
            'id' => 3,
            'slug' => 'square-silk-earth',
            'name' => 'Square Silk Earth',
            'category' => 'Square',
            'price' => 159000,
            'old_price' => 189000,
            'rating' => 4.9,
            'reviews' => 74,
            'tag' => 'Limited',
            'color' => 'from-[#b99a62] via-[#d2b99b] to-[#6f5146]',
            'image' => 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=85',
            'description' => 'Square silk dengan motif earthy yang elegan, lembut, dan nyaman dipakai sepanjang hari.',
        ],
        [
            'id' => 4,
            'slug' => 'inner-jersey-nude',
            'name' => 'Inner Jersey Nude',
            'category' => 'Inner',
            'price' => 59000,
            'old_price' => null,
            'rating' => 4.7,
            'reviews' => 52,
            'tag' => null,
            'color' => 'from-[#d7c1b4] via-[#f4e9dd] to-[#a88b7b]',
            'image' => 'https://images.unsplash.com/photo-1610652492500-ded49ceeb378?auto=format&fit=crop&w=900&q=85',
            'description' => 'Inner jersey yang adem dan elastis untuk membuat hijab tetap rapi dari pagi hingga malam.',
        ],
        [
            'id' => 5,
            'slug' => 'pashmina-cloud-cream',
            'name' => 'Pashmina Cloud Cream',
            'category' => 'Pashmina',
            'price' => 129000,
            'old_price' => null,
            'rating' => 4.8,
            'reviews' => 41,
            'tag' => 'New arrival',
            'color' => 'from-[#f5eadc] via-[#fffaf4] to-[#d8c8b7]',
            'image' => 'https://images.unsplash.com/photo-1605763240000-7e93b172d754?auto=format&fit=crop&w=900&q=85',
            'description' => 'Warna cream yang timeless dengan material flowy untuk tampilan effortless dan bersih.',
        ],
        [
            'id' => 6,
            'slug' => 'voal-mauve-dream',
            'name' => 'Voal Mauve Dream',
            'category' => 'Voal',
            'price' => 109000,
            'old_price' => null,
            'rating' => 4.8,
            'reviews' => 63,
            'tag' => null,
            'color' => 'from-[#c6b3c6] via-[#eee2ec] to-[#8f7895]',
            'image' => 'https://images.unsplash.com/photo-1590736969955-71cc94901144?auto=format&fit=crop&w=900&q=85',
            'description' => 'Voal ringan berwarna mauve yang memberi sentuhan lembut dan modern pada setiap outfit.',
        ],
    ],
    'reviews' => [
        [
            'name' => 'Nadia Rahma',
            'initials' => 'NR',
            'rating' => 5,
            'product' => 'Pashmina Satin Moonlight',
            'quote' => 'Bahannya jatuh dan tidak mudah kusut. Warnanya juga persis seperti foto.',
        ],
        [
            'name' => 'Alya Putri',
            'initials' => 'AP',
            'rating' => 5,
            'product' => 'Voal Paris Rose',
            'quote' => 'Ringan dipakai seharian dan packing-nya cantik. Pasti repeat order.',
        ],
        [
            'name' => 'Salsa Mahira',
            'initials' => 'SM',
            'rating' => 4,
            'product' => 'Square Silk Earth',
            'quote' => 'Motifnya elegan dan mudah dipadukan untuk acara formal maupun casual.',
        ],
    ],
];
