@extends('layouts.app')

@section('title', 'Profile — Kembang Hijab')

@section('content')
    <section class="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8">
        <div class="border-b border-black pb-6"><p class="text-xs font-bold uppercase tracking-[.2em] text-[#faa21f]">Your account</p><h1 class="mt-3 text-4xl font-bold uppercase">My profile</h1></div>
        <div class="mt-8 grid gap-5 sm:grid-cols-3"><a href="{{ route('orders.index') }}" class="arcade-card hover:border-black"><span class="text-xs text-[#737373]">ORDERS</span><strong class="mt-3 block text-3xl">{{ count($orders) }}</strong><span class="mt-2 block text-sm">View order history ↗</span></a><a href="{{ route('wishlist.index') }}" class="arcade-card hover:border-black"><span class="text-xs text-[#737373]">WISHLIST</span><strong class="mt-3 block text-3xl">{{ $wishlistCount }}</strong><span class="mt-2 block text-sm">Saved pieces ↗</span></a><a href="{{ route('addresses.index') }}" class="arcade-card hover:border-black"><span class="text-xs text-[#737373]">DELIVERY</span><strong class="mt-3 block text-3xl">+</strong><span class="mt-2 block text-sm">Manage addresses ↗</span></a></div>
        <div class="mt-8 grid gap-5 lg:grid-cols-2"><section class="arcade-card"><h2 class="text-lg font-bold uppercase">Personal details</h2><div class="mt-5 grid gap-4"><label class="text-sm">Name<input class="mt-2 w-full border border-black bg-[#f3e5df] px-3 py-3" placeholder="Your name"></label><label class="text-sm">Email<input class="mt-2 w-full border border-black bg-[#f3e5df] px-3 py-3" type="email" placeholder="you@example.com"></label><label class="text-sm">Phone<input class="mt-2 w-full border border-black bg-[#f3e5df] px-3 py-3" placeholder="08..." autocomplete="tel"></label><button class="arcade-button arcade-button-primary uppercase" type="button">Save details</button></div></section><section class="arcade-card"><h2 class="text-lg font-bold uppercase">Need help?</h2><p class="mt-4 text-sm leading-6 text-[#737373]">Our customer care team can help with products, payments, and delivery.</p><a href="{{ route('chat.index') }}" class="arcade-button arcade-button-ghost mt-5 inline-flex uppercase">Open customer care</a></section></div>
    </section>
@endsection
