@extends('layouts.app')

@section('title', 'About — Kembang Hijab')
@section('meta_description', 'The story behind Kembang Hijab and our approach to everyday comfort.')

@section('content')
    <section class="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-20"><div class="grid gap-8 lg:grid-cols-[1fr_360px]"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-[#faa21f]">About the label</p><h1 class="mt-4 max-w-4xl text-5xl font-bold uppercase leading-[1.05] sm:text-7xl">Make room for every version of you.</h1><p class="mt-7 max-w-2xl text-base leading-8 text-[#333333]">Kembang Hijab lahir dari keyakinan sederhana: pakaian yang baik harus terasa nyaman sebelum terlihat indah. Kami membuat hijab untuk ritme nyata, bukan hanya untuk satu momen.</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('products.index') }}" class="arcade-button arcade-button-primary uppercase">Shop the collection ↗</a><a href="{{ route('chat.index') }}" class="arcade-button arcade-button-ghost uppercase">Talk to us</a></div></div><div class="arcade-checkerboard border border-black p-5"><div class="flex min-h-80 flex-col justify-between border border-black bg-[#f3e5df] p-5"><span class="text-4xl font-bold">+</span><div><p class="text-xs uppercase text-[#737373]">Our point of view</p><p class="mt-3 text-lg font-bold uppercase">Less noise. More feeling.</p></div></div></div></div></section>

    <section class="border-y border-black"><div class="mx-auto grid max-w-7xl gap-0 sm:grid-cols-3 sm:divide-x sm:divide-black"><article class="px-4 py-10 sm:px-8"><span class="text-3xl font-bold">01</span><h2 class="mt-8 text-lg font-bold uppercase">Thoughtful fabrics</h2><p class="mt-3 text-sm leading-7 text-[#737373]">Material yang ringan, lembut, dan tetap nyaman setelah dipakai sepanjang hari.</p></article><article class="border-t border-black px-4 py-10 sm:border-t-0 sm:px-8"><span class="text-3xl font-bold">02</span><h2 class="mt-8 text-lg font-bold uppercase">Made with care</h2><p class="mt-3 text-sm leading-7 text-[#737373]">Setiap detail dipilih untuk terasa sederhana, fungsional, dan mudah dipakai berulang kali.</p></article><article class="border-t border-black px-4 py-10 sm:border-t-0 sm:px-8"><span class="text-3xl font-bold">03</span><h2 class="mt-8 text-lg font-bold uppercase">Everyday expression</h2><p class="mt-3 text-sm leading-7 text-[#737373]">Tidak ada satu cara yang benar untuk tampil. Koleksi kami dibuat untuk mengikuti caramu.</p></article></div></section>

    <section class="mx-auto max-w-3xl px-4 py-20 text-center sm:px-6 lg:px-8"><p class="text-xs font-bold uppercase tracking-[.2em] text-[#faa21f]">Come as you are</p><h2 class="mt-4 text-3xl font-bold uppercase sm:text-5xl">Your rhythm is the signature.</h2><p class="mt-5 text-sm leading-7 text-[#737373]">Terima kasih sudah menjadi bagian dari perjalanan Kembang Hijab.</p></section>
@endsection
