@extends('layouts.app')

@section('title', 'Kembang Hijab — Everyday pieces, made to move')
@section('meta_description', 'Kembang Hijab makes comfortable, expressive everyday hijab for every version of you.')

@section('content')
    <section class="mx-auto grid max-w-7xl gap-6 px-4 py-8 sm:px-6 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-12">
        <div class="arcade-checkerboard flex min-h-[520px] flex-col justify-between border border-black p-6 sm:p-10">
            <div class="flex items-start justify-between gap-4"><span class="arcade-tag bg-[#f3e5df]">NEW DROP / 2026</span><span class="text-sm text-white">01 / 04</span></div>
            <div class="mx-auto w-full max-w-sm border border-black bg-[#f3e5df] p-3"><img src="{{ $products[0]['image'] ?? '' }}" alt="{{ $products[0]['name'] ?? 'Kembang Hijab collection' }}" width="900" height="1125" fetchpriority="high" class="aspect-[4/5] w-full object-cover"></div>
            <div class="flex items-center justify-between text-sm font-bold text-white"><span>THE EVERYDAY EDIT</span><span aria-hidden="true">+</span></div>
        </div>
        <div class="flex flex-col justify-center py-4 lg:pl-8"><p class="text-xs font-bold uppercase tracking-[.2em] text-[#faa21f]">Kembang Hijab / Independent label</p><h1 class="mt-4 text-5xl font-bold uppercase leading-[1.05] sm:text-7xl">Wear your own rhythm.</h1><p class="mt-6 max-w-lg text-base leading-7 text-[#333333]">Hijab yang ringan, berani, dan dibuat untuk bergerak bersama hari-harimu.</p><div class="mt-8 flex flex-wrap gap-3"><a href="{{ route('products.index') }}" class="arcade-button arcade-button-primary uppercase">Shop collection ↗</a><a href="{{ route('about') }}" class="arcade-button arcade-button-ghost uppercase">Our story</a></div><div class="mt-12 grid grid-cols-3 border-y border-black py-4 text-xs"><div><strong class="block text-lg">4.8</strong><span>community rating</span></div><div><strong class="block text-lg">24k+</strong><span>happy customers</span></div><div><strong class="block text-lg">100%</strong><span>everyday comfort</span></div></div></div>
    </section>

    <section class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div class="flex items-end justify-between border-b border-black pb-4"><div><p class="text-xs font-bold uppercase text-[#faa21f]">Browse the signal</p><h2 class="mt-2 text-2xl font-bold uppercase">Shop by category</h2></div><a href="{{ route('categories.index') }}" class="text-sm font-bold uppercase hover:underline">All categories ↗</a></div><div class="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">@foreach($categories as $category)<a href="{{ route('categories.show', $category['slug']) }}" class="arcade-card group min-h-40"><p class="text-xs text-[#737373]">0{{ $loop->iteration }}</p><h3 class="mt-8 text-xl font-bold uppercase group-hover:underline">{{ $category['name'] }}</h3><p class="mt-2 text-xs text-[#737373]">{{ $category['description'] }}</p></a>@endforeach</div></section>

    <section class="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div class="flex items-end justify-between border-b border-black pb-4"><div><p class="text-xs font-bold uppercase text-[#faa21f]">Product showcase</p><h2 class="mt-2 text-2xl font-bold uppercase">Latest pieces</h2></div><a href="{{ route('products.index') }}" class="text-sm font-bold uppercase hover:underline">Shop all ↗</a></div><div class="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">@foreach($products as $product)<article class="arcade-card group"><a href="{{ route('products.show', $product['slug']) }}"><div class="relative aspect-[4/5] overflow-hidden bg-[#e5e7eb]"><img src="{{ $product['image'] }}" alt="{{ $product['name'] }}" width="900" height="1125" loading="lazy" class="h-full w-full object-cover transition duration-300 group-hover:scale-105">@if($product['tag'])<span class="arcade-tag absolute left-3 top-3 bg-[#f3e5df]">{{ strtoupper($product['tag']) }}</span>@endif</div><div class="mt-3 flex items-start justify-between gap-3"><h3 class="text-sm font-bold uppercase">{{ $product['name'] }}</h3><span class="shrink-0 text-sm">Rp{{ number_format($product['price'], 0, ',', '.') }}</span></div></a><a href="{{ route('products.show', $product['slug']) }}" class="arcade-button arcade-button-primary mt-4 block text-center uppercase">Add to cart</a></article>@endforeach</div></section>

    <section class="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8"><div class="border-y border-black py-10 text-center"><p class="text-xs font-bold uppercase text-[#faa21f]">The Kembang belief</p><blockquote class="mx-auto mt-4 max-w-3xl text-2xl font-bold uppercase leading-tight sm:text-4xl">Good clothes make room for a good day.</blockquote><a href="{{ route('about') }}" class="mt-6 inline-flex arcade-button arcade-button-ghost uppercase">Read our story ↗</a></div></section>

    <section class="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div class="flex items-end justify-between border-b border-black pb-4"><div><p class="text-xs font-bold uppercase text-[#faa21f]">Community notes</p><h2 class="mt-2 text-2xl font-bold uppercase">Worn and loved</h2></div><a href="{{ route('reviews.index') }}" class="text-sm font-bold uppercase hover:underline">Read all ↗</a></div><div class="mt-5 grid gap-3 lg:grid-cols-3">@foreach($reviews as $review)<article class="arcade-card"><div class="flex justify-between gap-3"><strong class="text-sm uppercase">{{ $review['name'] }}</strong><span class="text-sm">{{ str_repeat('★', $review['rating']) }}</span></div><p class="mt-6 text-base leading-7">“{{ $review['quote'] }}”</p><p class="mt-5 text-xs uppercase text-[#737373]">{{ $review['product'] }}</p></article>@endforeach</div></section>
@endsection
